---
- name: Mount ISO for unattended SQL Server 2016 install
  hosts: localhost
  gather_facts: false
  connection: local

  vars_prompt:
    - name: vcenter_user
      prompt: "vCenter Username?"
      private: no

    - name: vcenter_pass
      prompt: "vCenter Password?"
      private: yes

    - name: vm_name
      prompt: "Name for new VM?"
      private: no

  tasks:
  - name: Mount ISO from datastore
    vmware_guest:
      hostname: < vCenter hostname or IP > # replace with your vCenter info
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
      validate_certs: no
      datacenter: < your ESXi data center name > # replace with your datacenter name from vCenter
      cluster: < your ESXi cluster name > # replace with your desired ESXi cluster location
      folder: </folder name for new VM> # the folder you want to place the VM
      name: '{{ vm_name }}' 
      cdrom:
        type: "iso"
        iso_path: "[<data store name>] <folder>/<iso file>.ISO" # replace with the path to your SQL Server ISO
    delegate_to: localhost
